# Generated by Django 6.0.1 on 2026-02-19 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meditation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='meditation_images/'),
        ),
        migrations.AddField(
            model_name='yoga',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='yoga_images/'),
        ),
    ]
